###### The motion planning interface

### Action Server Goal

# The final location to be reached in the plan.

Location target

---

### Action Server Result

# The plan, the list of location to reach the `target` given the current position.

Location[] plan

---

### Action Server Feedback

Location[] plan
